[tool.poetry]
name = "forest-analyzer"
version = "0.1.0"
description = "Textual forest data analyzer"
authors = ["ronikeuru <roni@three.consulting>"]
readme = "README.md"
packages = [{include = "forest_analyzer"}]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.22.0"
spatialite = "^0.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
